name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@0.0.4
    with:
      solution-file-path: 'Source/Starship-Expansion-Project.sln'
      use-ckan: true
      artifacts: GameData LICENSE* README* CHANGELOG* Extras
